[project]
name = "infocard-studio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.11.0",
    "autoawq>=0.2.9",
    "bitsandbytes>=0.48.2",
    "diffusers>=0.35.2",
    "dotenv>=0.9.9",
    "gigachat>=0.1.43",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "isort>=7.0.0",
    "kornia>=0.8.2",
    "langchain-core>=0.3.79",
    "langchain-gigachat>=0.3.12",
    "langgraph>=1.0.1",
    "pillow>=12.0.0",
    "pydantic>=2.12.4",
    "requests>=2.32.5",
    "timm>=1.0.22",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "transformers==4.56.2",
]
